export const NOTE = {
    RIGHT_CLICK: "NOTE_RIGHT_CLICK",
    LEFT_CLICK: "NOTE_LEFT_CLICK",
    LOOK: "NOTE_LOOK",
    HOLD: "NOTE_HOLD",
    DO_NOT_CLICK: "NOTE_DO_NOT_CLICK"
}

export const EFFECT = {
    INVERT: "INVERT",
    COLOR: "COLOR",
    EFFECT: "EFFECT",
    HOLOGRAM: "HOLOGRAM",
    MESSAGE: "MESSAGE",
    SPEED: "SPEED",
    TIME: "TIME"
}

export const EFFECT_ID = {
    SPEED: "SPEED",
    SLOWNESS: "SLOWNESS",
    HASTE: "HASTE",
    MINING_FATIGUE: "MINING_FATIGUE",
    STRENGTH: "STRENGTH",
    INSTANT_HEALTH: "INSTANT_HEALTH",
    INSTANT_DAMAGE: "INSTANT_DAMAGE",
    JUMP_BOOST: "JUMP_BOOST",
    NAUSEA: "NAUSEA",
    REGENERATION: "REGENERATION",
    RESISTANCE: "RESISTANCE",
    FIRE_RESISTANCE: "FIRE_RESISTANCE",
    WATER_BREATHING: "WATER_BREATHING",
    INVISIBILITY: "INVISIBILITY",
    BLINDNESS: "BLINDNESS",
    NIGHT_VISION: "NIGHT_VISION",
    HUNGER: "HUNGER",
    WEAKNESS: "WEAKNESS",
    POISON: "POISON",
    WITHER: "WITHER",
    HEALTH_BOOST: "HEALTH_BOOST",
    ABSORPTION: "ABSORPTION",
    SATURATION: "SATURATION",
    GLOWING: "GLOWING",
    LEVITATION: "LEVITATION",
    LUCK: "LUCK",
    UNLUCK: "UNLUCK"
}